In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_data.csv")

df.head()

         Date     Product     Category  Quantity  Sales  Profit
0  2026-01-10      Laptop  Electronics         5  55000   10000
1  2026-01-15      Mobile  Electronics         8  42000    8000
2  2026-02-05      Tablet  Electronics         6  28000    5000
3  2026-02-18  Headphones  Accessories        12  18000    3500
4  2026-03-08      Laptop  Electronics         7  65000   13000

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     str
 1   Product   10 non-null     str
 2   Category  10 non-null     str
 3   Quantity  10 non-null     int64
 4   Sales     10 non-null     int64
 5   Profit    10 non-null     int64
dtypes: int64(3), str(3)
memory usage: 612.0 bytes
None

In [4]:
print(df.isnull().sum())

Date        0
Product     0
Category    0
Quantity    0
Sales       0
Profit      0
dtype: int64

In [5]:
df = df.fillna("Not Available")

In [6]:
df.to_csv("cleaned_sales_data.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [7]:
cleaned_df = pd.read_csv("cleaned_sales_data.csv")

cleaned_df.head()

         Date     Product     Category  Quantity  Sales  Profit
0  2026-01-10      Laptop  Electronics         5  55000   10000
1  2026-01-15      Mobile  Electronics         8  42000    8000
2  2026-02-05      Tablet  Electronics         6  28000    5000
3  2026-02-18  Headphones  Accessories        12  18000    3500
4  2026-03-08      Laptop  Electronics         7  65000   13000

In [8]:
print("Original Dataset Shape:", pd.read_csv("sales_data.csv").shape)

print("Cleaned Dataset Shape:", cleaned_df.shape)

Original Dataset Shape: (10, 6)
Cleaned Dataset Shape: (10, 6)