In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Nithya", "Rahul", "Anu", "Arjun", "Meera"],
    "Age": [21, np.nan, 20, 23, np.nan],
    "Department": ["CSE", "ECE", "CSE", None, "CSE"],
    "Marks": [95, 88, np.nan, 79, 85]
}

df = pd.DataFrame(data)

df

     Name   Age Department  Marks
0  Nithya  21.0        CSE   95.0
1   Rahul   NaN        ECE   88.0
2     Anu  20.0        CSE    NaN
3   Arjun  23.0        NaN   79.0
4   Meera   NaN        CSE   85.0

In [3]:
df.isnull()

    Name    Age  Department  Marks
0  False  False       False  False
1  False   True       False  False
2  False  False       False   True
3  False  False        True  False
4  False   True       False  False

In [4]:
df.isnull().sum()

Name          0
Age           2
Department    1
Marks         1
dtype: int64

In [5]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [6]:
df["Department"] = df["Department"].fillna("Unknown")

In [7]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [8]:
df.dropna()

     Name        Age Department  Marks
0  Nithya  21.000000        CSE  95.00
1   Rahul  21.333333        ECE  88.00
2     Anu  20.000000        CSE  86.75
3   Arjun  23.000000    Unknown  79.00
4   Meera  21.333333        CSE  85.00

In [9]:
df.drop_duplicates()

     Name        Age Department  Marks
0  Nithya  21.000000        CSE  95.00
1   Rahul  21.333333        ECE  88.00
2     Anu  20.000000        CSE  86.75
3   Arjun  23.000000    Unknown  79.00
4   Meera  21.333333        CSE  85.00

In [10]:
df.rename(columns={"Marks": "Score"}, inplace=True)

df

     Name        Age Department  Score
0  Nithya  21.000000        CSE  95.00
1   Rahul  21.333333        ECE  88.00
2     Anu  20.000000        CSE  86.75
3   Arjun  23.000000    Unknown  79.00
4   Meera  21.333333        CSE  85.00

In [11]:
print(df.info())
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      float64
 2   Department  5 non-null      str
 3   Score       5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 292.0 bytes
None
             Age      Score
count   5.000000   5.000000
mean   21.333333  86.750000
std     1.080123   5.760859
min    20.000000  79.000000
25%    21.000000  85.000000
50%    21.333333  86.750000
75%    21.333333  88.000000
max    23.000000  95.000000

In [12]:
import pandas as pd
import numpy as np

employee = {
    "Employee": ["Alex", "John", "John", "Sara"],
    "Salary": [50000, np.nan, 45000, 60000],
    "Department": ["HR", "IT", "IT", None]
}

emp = pd.DataFrame(employee)

print(emp)

print(emp.isnull().sum())

emp["Salary"] = emp["Salary"].fillna(emp["Salary"].mean())

emp["Department"] = emp["Department"].fillna("Unknown")

emp = emp.drop_duplicates()

print(emp)

  Employee   Salary Department
0     Alex  50000.0         HR
1     John      NaN         IT
2     John  45000.0         IT
3     Sara  60000.0        NaN
Employee      0
Salary        1
Department    1
dtype: int64
  Employee        Salary Department
0     Alex  50000.000000         HR
1     John  51666.666667         IT
2     John  45000.000000         IT
3     Sara  60000.000000    Unknown