In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_data.csv")

df.head()

         Date     Product     Category  Quantity  Sales  Profit
0  2026-01-10      Laptop  Electronics         5  55000   10000
1  2026-01-15      Mobile  Electronics         8  42000    8000
2  2026-02-05      Tablet  Electronics         6  28000    5000
3  2026-02-18  Headphones  Accessories        12  18000    3500
4  2026-03-08      Laptop  Electronics         7  65000   13000

In [3]:
df[["Product", "Sales"]]

      Product  Sales
0      Laptop  55000
1      Mobile  42000
2      Tablet  28000
3  Headphones  18000
4      Laptop  65000
5      Mobile  48000
6       Watch  26000
7      Tablet  32000
8      Laptop  60000
9      Mobile  51000

In [4]:
high_sales = df[df["Sales"] > 40000]

high_sales

         Date Product     Category  Quantity  Sales  Profit
0  2026-01-10  Laptop  Electronics         5  55000   10000
1  2026-01-15  Mobile  Electronics         8  42000    8000
4  2026-03-08  Laptop  Electronics         7  65000   13000
5  2026-03-20  Mobile  Electronics        10  48000    9500
8  2026-05-10  Laptop  Electronics         6  60000   12000
9  2026-06-15  Mobile  Electronics        11  51000   10000

In [5]:
electronics = df[df["Category"] == "Electronics"]

electronics

         Date Product     Category  Quantity  Sales  Profit
0  2026-01-10  Laptop  Electronics         5  55000   10000
1  2026-01-15  Mobile  Electronics         8  42000    8000
2  2026-02-05  Tablet  Electronics         6  28000    5000
4  2026-03-08  Laptop  Electronics         7  65000   13000
5  2026-03-20  Mobile  Electronics        10  48000    9500
7  2026-04-22  Tablet  Electronics         8  32000    6000
8  2026-05-10  Laptop  Electronics         6  60000   12000
9  2026-06-15  Mobile  Electronics        11  51000   10000

In [6]:
df.sort_values(by="Sales")

         Date     Product     Category  Quantity  Sales  Profit
3  2026-02-18  Headphones  Accessories        12  18000    3500
6  2026-04-05       Watch  Accessories        15  26000    4800
2  2026-02-05      Tablet  Electronics         6  28000    5000
7  2026-04-22      Tablet  Electronics         8  32000    6000
1  2026-01-15      Mobile  Electronics         8  42000    8000
5  2026-03-20      Mobile  Electronics        10  48000    9500
9  2026-06-15      Mobile  Electronics        11  51000   10000
0  2026-01-10      Laptop  Electronics         5  55000   10000
8  2026-05-10      Laptop  Electronics         6  60000   12000
4  2026-03-08      Laptop  Electronics         7  65000   13000

In [7]:
df.sort_values(by="Sales", ascending=False)

         Date     Product     Category  Quantity  Sales  Profit
4  2026-03-08      Laptop  Electronics         7  65000   13000
8  2026-05-10      Laptop  Electronics         6  60000   12000
0  2026-01-10      Laptop  Electronics         5  55000   10000
9  2026-06-15      Mobile  Electronics        11  51000   10000
5  2026-03-20      Mobile  Electronics        10  48000    9500
1  2026-01-15      Mobile  Electronics         8  42000    8000
7  2026-04-22      Tablet  Electronics         8  32000    6000
2  2026-02-05      Tablet  Electronics         6  28000    5000
6  2026-04-05       Watch  Accessories        15  26000    4800
3  2026-02-18  Headphones  Accessories        12  18000    3500

In [ ]:
# Day 6 Summary

- Loaded the sales dataset.
- Selected specific columns.
- Filtered rows based on sales and category.
- Sorted the dataset in ascending and descending order.

**Expected Outcome:** Filtered dataset created.